CREATE TABLE [dbo].[CardTags]
(
	[Id] INT IDENTITY(1,1),
	CardId INT NOT NULL,
	Tag NVARCHAR(MAX) NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CardTags_CardId] FOREIGN KEY ([CardId]) REFERENCES [dbo].[Cards] ([Id])
)
