
USE [master]
GO

/****** Object:  Database [Memoraide]    Script Date: 10/20/2018 12:50:24 PM ******/
CREATE DATABASE [Memoraide]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Memoraide', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Memoraide.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Memoraide_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Memoraide_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Memoraide] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Memoraide].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Memoraide] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Memoraide] SET ARITHABORT OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Memoraide] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Memoraide] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Memoraide] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Memoraide] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Memoraide] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Memoraide] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Memoraide] SET  DISABLE_BROKER
GO

ALTER DATABASE [Memoraide] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Memoraide] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Memoraide] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Memoraide] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Memoraide] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Memoraide] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Memoraide] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Memoraide] SET RECOVERY FULL
GO

ALTER DATABASE [Memoraide] SET  MULTI_USER
GO

ALTER DATABASE [Memoraide] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Memoraide] SET DB_CHAINING OFF
GO

ALTER DATABASE [Memoraide] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Memoraide] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Memoraide] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Memoraide] SET  READ_WRITE
GO

