
USE [master]
GO

/****** Object:  Database [Memoraide]    Script Date: 10/20/2018 12:50:24 PM ******/
CREATE DATABASE [Memoraide]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Memoraide', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Memoraide.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Memoraide_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Memoraide_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Memoraide] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Memoraide].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Memoraide] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Memoraide] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Memoraide] SET ARITHABORT OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Memoraide] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Memoraide] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Memoraide] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Memoraide] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Memoraide] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Memoraide] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Memoraide] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Memoraide] SET  DISABLE_BROKER
GO

ALTER DATABASE [Memoraide] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Memoraide] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Memoraide] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Memoraide] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Memoraide] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Memoraide] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Memoraide] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Memoraide] SET RECOVERY FULL
GO

ALTER DATABASE [Memoraide] SET  MULTI_USER
GO

ALTER DATABASE [Memoraide] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Memoraide] SET DB_CHAINING OFF
GO

ALTER DATABASE [Memoraide] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Memoraide] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Memoraide] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Memoraide] SET  READ_WRITE
GO

USE [Memoraide]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 10/6/2018 8:02:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


SET ANSI_PADDING ON
GO;

CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[IsBanned] [bit] NULL,
	[BannedDate] [datetime] NULL,
	[IsDeleted] [bit] NULL,
	[DeletedDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO;


CREATE TABLE [dbo].[Cards](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DeckId] [int] NOT NULL,
	[Question] [varchar](max) NOT NULL,
	[Answer] [varchar](max) NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[IsDeleted] [bit] NULL,
	[DateDeleted] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO;


ALTER TABLE [dbo].[Cards]  WITH CHECK ADD  CONSTRAINT [FK_DeckId] FOREIGN KEY([DeckId])
REFERENCES [dbo].[Decks] ([Id])
GO;

ALTER TABLE [dbo].[Cards] CHECK CONSTRAINT [FK_DeckId]
GO;

CREATE TABLE [dbo].[Decks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[UserId] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[IsDeleted] [bit] NULL,
	[DateDeleted] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO;

ALTER TABLE [dbo].[Decks]  WITH CHECK ADD  CONSTRAINT [FK_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO;

ALTER TABLE [dbo].[Decks] CHECK CONSTRAINT [FK_UserId]
GO;

CREATE TABLE [dbo].[UserDecks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[DeckId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO;

ALTER TABLE [dbo].[UserDecks]  WITH CHECK ADD  CONSTRAINT [FK_UserDecks_DeckId] FOREIGN KEY([DeckId])
REFERENCES [dbo].[Decks] ([Id])
GO;

ALTER TABLE [dbo].[UserDecks] CHECK CONSTRAINT [FK_UserDecks_DeckId]
GO;

ALTER TABLE [dbo].[UserDecks]  WITH CHECK ADD  CONSTRAINT [FK_UserDecks_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO;

ALTER TABLE [dbo].[UserDecks] CHECK CONSTRAINT [FK_UserDecks_UserId]
GO;

CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO;

CREATE TABLE [dbo].[UserRoles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO;



GO
