USE [Memoraide]
GO

IF EXISTS (SELECT TOP 1 * FROM dbo.CardTags)
BEGIN
	TRUNCATE TABLE dbo.CardTags
	DROP TABLE dbo.CardTags
END

IF EXISTS (SELECT TOP 1 * FROM dbo.Cards)
BEGIN
	TRUNCATE TABLE dbo.Cards
	DROP TABLE dbo.Cards
END

IF EXISTS (SELECT TOP 1 * FROM dbo.UserDecks)
BEGIN
	TRUNCATE TABLE dbo.UserDecks
	DROP TABLE dbo.UserDecks
END

IF EXISTS (SELECT TOP 1 * FROM dbo.Decks)
BEGIN
	TRUNCATE TABLE dbo.Decks
	DROP TABLE dbo.Decks
END

IF EXISTS (SELECT TOP 1 * FROM dbo.UserRoles)
BEGIN
	TRUNCATE TABLE dbo.UserRoles
	DROP TABLE dbo.UserRoles
END

IF EXISTS (SELECT TOP 1 * FROM dbo.Roles)
BEGIN
	TRUNCATE TABLE dbo.Roles
	DROP TABLE dbo.Roles
END

IF EXISTS (SELECT TOP 1 * FROM dbo.Users)
BEGIN
	TRUNCATE TABLE dbo.Users
	DROP TABLE dbo.Users
END

CREATE TABLE [dbo].[Users](
	[Id]          INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]   VARCHAR (50)   NOT NULL,
    [LastName]    VARCHAR (50)   NOT NULL,
    [Email]       NVARCHAR (100) NOT NULL,
    [Username]	  VARCHAR(50) NOT NULL, 
    [Password]	  NVARCHAR(MAX) NOT NULL, 
    [DateCreated] DATETIME		 NULL, 
    [IsBanned]    BIT            NULL,
    [DateBanned]  DATETIME       NULL,
    [IsDeleted]   BIT            NULL,
    [DateDeleted] DATETIME       NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 


CREATE TABLE [dbo].[Cards](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DeckId] [int] NOT NULL,
	[Question] [varchar](max) NOT NULL,
	[Answer] [varchar](max) NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[IsDeleted] [bit] NULL,
	[DateDeleted] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

 


ALTER TABLE [dbo].[Cards]  WITH CHECK ADD  CONSTRAINT [FK_DeckId] FOREIGN KEY([DeckId])
REFERENCES [dbo].[Decks] ([Id])
 

ALTER TABLE [dbo].[Cards] CHECK CONSTRAINT [FK_DeckId]
 

CREATE TABLE [dbo].[Decks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[UserId] [int] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
	[IsDeleted] [bit] NULL,
	[DateDeleted] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 

ALTER TABLE [dbo].[Decks]  WITH CHECK ADD  CONSTRAINT [FK_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
 

ALTER TABLE [dbo].[Decks] CHECK CONSTRAINT [FK_UserId]
 

CREATE TABLE [dbo].[UserDecks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[DeckId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 

ALTER TABLE [dbo].[UserDecks]  WITH CHECK ADD  CONSTRAINT [FK_UserDecks_DeckId] FOREIGN KEY([DeckId])
REFERENCES [dbo].[Decks] ([Id])
 

ALTER TABLE [dbo].[UserDecks] CHECK CONSTRAINT [FK_UserDecks_DeckId]
 

ALTER TABLE [dbo].[UserDecks]  WITH CHECK ADD  CONSTRAINT [FK_UserDecks_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
 

ALTER TABLE [dbo].[UserDecks] CHECK CONSTRAINT [FK_UserDecks_UserId]
 

CREATE TABLE [dbo].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 

CREATE TABLE [dbo].[UserRoles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 

CREATE TABLE [dbo].[CardTags]
(
	[Id] INT IDENTITY(1,1),
	CardId INT NOT NULL,
	Tag NVARCHAR(MAX) NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CardTags_CardId] FOREIGN KEY ([CardId]) REFERENCES [dbo].[Cards] ([Id])
)

GO
